### login 

POST  http://localhost:3000/login 
Content-Type: application/json

{"identifier":"j.fathi1998@gmail.com" , "password" :"Test1234" }


### signup 

POST  http://localhost:3000/signup 
Content-Type: application/json

{"username":"sdfasdaf" , "password":"sdfadsfa8d28as5f8" , "email":"shdfa@gmail.com" }


### forgot 

POST  http://localhost:3000/forgot 
Content-Type: application/json

{"identifier":"j.fathi1998@gmail.com"}


### recover 

POST  http://localhost:3000/recover 
Content-Type: application/json

{"token":"a534ecfe-044d-428a-9e70-409f77bbdd2f" , "password":"Test1234"}

### info 

GET  http://localhost:3000/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMjI1YzE1OS01N2E1LTQ1NTYtYmUyNy00ZDQyYjBiZWM5MzAiLCJpYXQiOjE3MDUxMzA2MDgsImV4cCI6MTcwNTEzNDIwOH0.FChyt9b9fXXhDPfKUfo8Hc-duME-MnGz3sP3PNerAGA
